blog/urls.py
from django.urls import path, include
from . import views

app_name = "blog"
urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
]

first_story/urls.py
from django.urls import path, include
from . import views

app_name = "first_story"
urlpatterns = [
    path('', views.story1, name="story1"),
]

story_5/urls.py
from django.urls import path
from .views import (
    MatkulListView,
    MatkulDetailView,
    MatkulCreateView,
    MatkulUpdateView,
    MatkulDeleteView
)
from . import views

urlpatterns = [
    path('', MatkulListView.as_view(), name='home'),
    path('matkul/<int:pk>/', MatkulDetailView.as_view(), name='matkul-detail'),
    path('matkul/create/', MatkulCreateView.as_view(), name='matkul-create'),
    path('matkul/<int:pk>/update/', MatkulUpdateView.as_view(), name='matkul-update'),
    path('matkul/<int:pk>/delete/', MatkulDeleteView.as_view(), name='matkul-delete'),
]

story_ppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('story1/', include('first_story.urls')),
    path('story_5/', include('story_5.urls')),
]

blog/models.py
from django.db import models

# Create your models here.

first_story/models.py
from django.db import models

# Create your models here.

story_5/models.py
from django.db import models
from django.urls import reverse

class Matkul(models.Model):
    nama = models.CharField(max_length=100)
    dosen = models.CharField(max_length=100)
    sks = models.IntegerField()
    semester = models.CharField(max_length=100)
    ruangan = models.CharField(max_length=100)
    deskripsi = models.TextField()

    def get_absolute_url(self):
        return reverse('home')

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
    return render(request, 'blog/home.html')

def contact(request):
    return render(request, 'blog/contact.html') 

first_story/views.py
from django.shortcuts import render
from django.http import HttpResponse

def story1(request):
    return render(request, 'first_story/story1.html')

story_5/views.py
from django.shortcuts import render
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Matkul

class MatkulListView(ListView):
    model = Matkul
    template_name = 'story_5/home.html'
    context_object_name = 'matkuls'

class MatkulDetailView(DetailView):
    model = Matkul

class MatkulCreateView(CreateView):
    model = Matkul
    fields = ['nama', 'dosen', 'sks', 'semester', 'ruangan', 'deskripsi']

class MatkulUpdateView(UpdateView):
    model = Matkul
    fields = ['nama', 'dosen', 'sks', 'semester', 'ruangan', 'deskripsi']

class MatkulDeleteView(DeleteView):
    model = Matkul
    success_url = '/story_5'

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="icon" href="/static/logo/surveycorpslogo.png">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'blog/bootstrap.min.css' %}">
        <link rel='stylesheet' type='text/css' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css'>
        <link rel="stylesheet" href="{% static 'blog/style.css' %}">
        <title>Ardi Nusantara</title>
    </head>
    <body>
        <!-- Nav bar -->
        <nav class="navbar navbar-expand-md navbar-dark top-bar-color fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/"><img class="rounded-circle" src="/static/images/Foto.jpg" alt="Foto Saya" width="40" height="40"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="/">Home</a>
                        <a class="nav-item nav-link" href="/contact">Contact Me</a>
                        <a class="nav-item nav-link" href="{% url 'first_story:story1' %}">Story 1</a>
                        <a class="nav-item nav-link" href="{% url 'home' %}">Story 5</a>
                    </div>
                </div>
            </div>
        </nav>

        <br>

        <main role="main" class="container">
            {% block content %}{% endblock %}
        </main>

        <!-- Footer -->
        <footer id="footer">
            <div class="container">
                <div class="row text-light text-center py-4 justify-content-center">
                    <p style="color: white">Punya interest yang sama dengan saya? Ingin mengobrol-ngobrol? Kontak saya di:</p>
                    <div class="col-sm-10 col-md-8 col-lg-6">
                        <ul class="social pt-3">
                            <li><a href="https://web.facebook.com/lazuardi.pratama.92/" rel="noopener noreferrer" target="_blank"><em class="fa fa-facebook"></em></a></li>
                            <li><a href="https://www.instagram.com/ardi_nusantara/" rel="noopener noreferrer" target="_blank"><em class="fa fa-instagram"></em></a></li>
                            <li><a href="https://twitter.com/ardippnusantara/" rel="noopener noreferrer" target="_blank"><em class="fa fa-twitter"></em></a></li>
                            <li><a href="https://www.linkedin.com/in/ardi-nusantara-5282971a3/" rel="noopener noreferrer" target="_blank"><em class="fa fa-linkedin"></em></a></li>
                        </ul>
                    </div>
                </div>
            </div> 
        </footer>
    </body>
</html>

blog/templates/blog/contact.html
{% extends "blog/base.html" %}
{% block content %}
<div class="site-inner">
    <div class="content-sidebar-wrap">
        <main class="content">
                <header class="entry-header"><h1 class="entry-title" style="text-align: center;" itemprop="headline">Contact</h1></header>
                <div class="entry-content" itemprop="text">
                    <div role="form" class="wpcf7" id="wpcf7-f864-p865-o1" lang="en-US" dir="ltr">
                        <div class="screen-reader-response" role="alert" aria-live="polite"></div>
                        <form action="/contact#wpcf7-f864-p865-o1" method="post" class="wpcf7-form init" novalidate="novalidate">
                            <div style="display: none;">
                                <input type="hidden" name="_wpcf7" value="864" />
                                <input type="hidden" name="_wpcf7_version" value="5.2.2" />
                                <input type="hidden" name="_wpcf7_locale" value="en_US" />
                                <input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f864-p865-o1" />
                                <input type="hidden" name="_wpcf7_container_post" value="865" />
                                <input type="hidden" name="_wpcf7_posted_data_hash" value="" />
                            </div>
                            <div class="wpcf7-response-output" role="alert" aria-hidden="true"></div>
                            <p>Name:<br />
                                <span class="wpcf7-form-control-wrap your-name"><input type="text" name="your-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true" aria-invalid="false" /></span> </p>
                            <p>Email:<br />
                                <span class="wpcf7-form-control-wrap your-email"><input type="email" name="your-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" aria-required="true" aria-invalid="false" /></span> </p>
                            <p>Subject:<br />
                                <span class="wpcf7-form-control-wrap your-subject"><input type="text" name="your-subject" value="" size="40" class="wpcf7-form-control wpcf7-text" aria-invalid="false" /></span> </p>
                            <p>Message:<br />
                                <span class="wpcf7-form-control-wrap your-message"><textarea name="your-message" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea" aria-invalid="false"></textarea></span> </p>
                            <p><input type="submit" value="Send" class="wpcf7-form-control wpcf7-submit" /></p>
                        </form>
                    </div>
                </div>
        </main>
    </div>
</div> 
{% endblock content %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
<div class="content">
    <div class="container text-center mt-4">
        <div id="foto">
            <img class="rounded-circle" src="/static/images/Foto.jpg" alt="Foto Saya">
        </div><br>
        <h2>Lazuardi Pratama Putra Nusantara</a></h2>
        <p>Computer Science Student | Universitas Indonesia</p>
    </div><br>
    
    <div class="selection">
        <div class="container">
            <div class="content-section" style="border-radius: 20px">
                    <h4>Tentang Saya</h4>
                    <p>Saya adalah seorang pelajar angkatan 2019 di Universitas Indonesia yang sedang menjalani pendidikan S1 Ilmu Komputer. 
                        Saya adalah orang yang memiliki rasa ingin tahu yang tinggi. Saya hobi membaca komik dan bermain game. 
                    </p>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="content-section" style="border-radius: 20px">
                        <div class="h4 mt-0 title"><h4>Riwayat Pendidikan</h4></div>
                        <div class="row">
                            <div class="col-sm-4"><strong>2007 - 2008</strong></div>
                            <div class="col-sm-8">SD Pertiwi Sumatera Utara</div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-sm-4"><strong>2008 - 2010</strong></div>
                            <div class="col-sm-8">SDIT Al-Kahfi Jakarta</div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-sm-4"><strong>2010 - 2013</strong></div>
                            <div class="col-sm-8">SDIT Baitussalam Jawa Barat</div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-sm-4"><strong>2013 - 2016</strong></div>
                            <div class="col-sm-8">SMP Islam Al-Hamidiyah</div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-sm-4"><strong>2016 - 2019</strong></div>
                            <div class="col-sm-8">SMAN 1 Depok</div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-sm-4"><strong>2019 - Sekarang</strong></div>
                            <div class="col-sm-8">Universitas Indonesia</div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="content-section" style="border-radius: 20px">
                        <div class="h4 mt-0 title"><h4>Interest & Skills</h4></div>
                        <p>Saya mahir dalam menggunakan Python dan Java. Sekarang saya sedang mendalami HTML dan CSS. 
                            Saya memiliki interest pada manga, anime, dan mobile game.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><br><br><br>
{% endblock content %}

first_story/templates/first_story/story1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <style>
            .Foto{
                text-align: center;
            }
            
            .Foto img{
                border-radius: 50%;
                border: 2px solid;
                margin-left: auto;
                margin-right: auto;
            }
        </style>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'first_story/story1.css' %}">
        <title>Story PPW</title>
    </head>
    <body>
        <!-- Nav bar -->
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                    <a class="navbar-brand mr-4" href="/">Ardi's PPW Story</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <div class="navbar-nav mr-auto">
                            <a class="nav-item nav-link" href="/">Home</a>
                        </div>
                        <!-- Navbar Right Side -->
                        <div class="navbar-nav">
                            <table id="media">
                                <tr>
                                    <td>
                                        <a href="https://web.facebook.com/lazuardi.pratama.92/">
                                            <img src="https://image.flaticon.com/icons/png/512/59/59439.png" alt="Facebook Saya" width="50" height="50">
                                        </a>
                                    </td>
                    
                                    <td>
                                        <a href="https://www.instagram.com/ardi_nusantara/">
                                            <img src="https://downloadfreesvgicons.com/icons/social-media-icons/svg-instagram-logo-icon-1/svg-instagram-logo-icon-1.svg" alt="Instagram Saya" width="50" height="50">
                                        </a>
                                    </td>
                    
                                    <td>
                                        <a href="https://twitter.com/ardippnusantara/">
                                            <img src="https://image.flaticon.com/icons/svg/60/60580.svg" alt="Twitter Saya" width="50" height="50">
                                        </a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <main role="main" class="container">
            <div class="row">
                <div class="col-md-12">
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="Foto">
                                <img src=https://maung.id/static/3379cb56d691cb522964a6052b55089e/9f583/TH28.jpg alt="Foto Saya" width="150" height="150">
                            </div>
                            <h2 class="article-title">Lazuardi Pratama Putra Nusantara</a></h2>
                            <p class="article-content">1906398225 | Fakultas Ilmu Komputer Universitas Indonesia | Maung 2019</p>
                        </div>
                    </article>
                </div>
                <div class="col-md-6">
                    <div class="content-section">
                        <h4>Sedikit Tentang Saya</h4>
                        <p>Saya adalah orang yang memiliki rasa ingin tahu yang tinggi. Saya hobi membaca komik dan bermain game. Motto hidup saya adalah "play it smart".</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <article class="media content-section">
                        <div class="media-body">
                            <h4>Riwayat Pendidikan</h4>
                            <table>
                                <tr>
                                    <th>Tahun</th>
                                    <td rowspan=7>&nbsp;</td>
                                    <th>Tempat Pendidikan</th>
                                </tr>
                                <tr>
                                    <td>2007 - 2008</td>
                                    <td>SD Pertiwi Sumatera Utara</td>
                                </tr>
                                <tr>
                                    <td>2008 - 2010</td>
                                    <td>SDIT Al-Kahfi Jakarta</td>
                                </tr>
                                <tr>
                                    <td>2010 - 2013</td>
                                    <td>SDIT Baitussalam Jawa Barat</td>
                                </tr>
                                <tr>
                                    <td>2013 - 2016</td>
                                    <td>SMP Islam Al-Hamidiyah</td>
                                </tr>
                                <tr>
                                    <td>2016 - 2019</td>
                                    <td>SMAN 1 Depok</td>
                                </tr>
                                <tr>
                                    <td>2019 - Sekarang</td>
                                    <td>Fakultas Ilmu Komputer Universitas Indonesia</td>
                                </tr>
                            </table>
                        </div>
                    </article>
                </div>
                
            </div>
        </main>
        
    </body>
</html>

story_5/templates/story_5/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="icon" href="/static/logo/surveycorpslogo.png">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'story_5/bootstrap.min.css' %}">
        <link rel='stylesheet' type='text/css' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css'>
        <link rel="stylesheet" href="{% static 'story_5/style.css' %}">
        <title>Ardi Nusantara</title>
    </head>
    <body>
        <!-- Nav bar -->
        <nav class="navbar navbar-expand-md navbar-dark top-bar-color fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="{% url 'blog:home' %}"><img class="rounded-circle" src="/static/images/Foto.jpg" alt="Foto Saya" width="40" height="40"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'blog:home' %}">Home</a>
                        <a class="nav-item nav-link" href="{% url 'home' %}">Daftar Matkul</a>
                        <a class="nav-item nav-link" href="{% url 'matkul-create' %}">Tambah Matkul</a>
                    </div>
                </div>
            </div>
        </nav>

        <br>

        <main role="main" class="container">
            {% block content %}{% endblock %}
        </main>
    </body>
</html>

story_5/templates/story_5/home.html
{% extends "story_5/base.html" %}
{% block content %}
    {% for matkul in matkuls %}
        <div class="container">
            <div class="content-section" style="border-radius: 20px">
                <legend class="border-bottom mb-4"><h2><a href="{% url 'matkul-detail' matkul.id %}">{{ matkul.nama }}</a></h2></legend>
                <p>{{ matkul.dosen }}</p>
                <p>{{ matkul.semester }}</p>
            </div>
        </div>
        
    {% endfor %}
{% endblock content %}

story_5/templates/story_5/matkul_confirm_delete.html
{% extends "story_5/base.html" %}
{% block content %}
    <div class="container">
        <div class="content-section" style="border-radius: 20px">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Hapus Matkul</legend>
                    <h2>Apakah kamu yakin ingin menghapus matkul "{{ object.nama }}"?</h2>
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-danger" type="submit">Ya!, Hapus</button>
                    <a class="btn btn-outline-secondary" href="{% url 'matkul-detail' object.id %}">Gak jadi deh</a>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

story_5/templates/story_5/matkul_detail.html
{% extends "story_5/base.html" %}
{% block content %}
  <div class="container">
    <div class="content-section" style="border-radius: 20px">
      <legend class="border-bottom mb-4"><h2>Mata Kuliah : {{ object.nama }}</h2></legend>
      <h4>Semester  : {{ object.semester }}</h4>
      <h4>Dosen     : {{ object.dosen }}</h4>
      <h4>SKS       : {{ object.sks }}</h4>
      <h4>Ruangan   : {{ object.ruangan }}</h4>
      <p>Deskripsi  : {{ object.deskripsi }}</p>
      <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'matkul-update' object.id %}">Update</a>
      <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'matkul-delete' object.id %}">Delete</a>
    </div>
</div>
{% endblock content %}

story_5/templates/story_5/matkul_form.html
{% extends "story_5/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <div class="content-section" style="border-radius: 20px">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Tambah Matkul</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Gas!</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}